import type { Request, Response, NextFunction } from 'express';
import express from 'express';
import type { Queue } from "bullmq";
import { getDecisions, getStats } from "./db/decisions";
import { agentWallet } from "./services/wallet";
import { hashEvent } from "./services/fraud";
import { aiProvider } from "./services/aiProvider";
import type { DeliveryEvent } from "./types";

const router = express.Router();

// Middleware for JSON parsing and CORS
router.use(express.json());
router.use((req: Request, res: Response, next: NextFunction) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type");
    next();
});

// // Handle preflight requests
// router.options("*", (req: Request, res: Response) => {
//     res.sendStatus(204);
// });

// ── GET /health ───────────────────────────────────────────────────────
router.get("/health", async (req: Request, res: Response) => {
    const wallet = await agentWallet.getStatus().catch(() => null);
    res.json({ status: "ACTIVE", timestamp: new Date().toISOString(), wallet });
});

// ── GET /agent/status ─────────────────────────────────────────────────
router.get("/agent/status", async (req: Request, res: Response) => {
    const [wallet, stats, queueDepth] = await Promise.all([
        agentWallet.getStatus(),
        getStats(),
        // queue will be passed from the main app
        req.app.locals.queue.count(),
    ]);
    res.json({
        agent: {
            status: "AUTONOMOUS",
            contract: process.env["CONTRACT_ADDRESS"] ?? "not set",
            wallet,
            queue: { depth: queueDepth },
        },
        statistics: stats,
    });
});

// ── GET /agent/wdk/status ────────────────────────────────────────────────
router.get("/agent/wdk/status", async (req: Request, res: Response) => {
    const wallet = await agentWallet.getStatus();
    const supportedChains = await agentWallet.getSupportedChains();
    const seedPhrase = agentWallet.getSeedPhrase();

    res.json({
        wallet: {
            ...wallet,
            supportedChains,
            hasSeedPhrase: !!seedPhrase,
            seedPhraseLength: seedPhrase.length,
        },
        features: {
            multiChain: supportedChains.length > 1,
            wdkEnabled: true,
            autoGenerated: wallet.seedPhraseGenerated,
        }
    });
});

// ── GET /agent/ai/status ─────────────────────────────────────────────────
router.get("/agent/ai/status", (req: Request, res: Response) => {
    res.json(aiProvider.getStatus());
});

// ── POST /agent/ai/switch ─────────────────────────────────────────────────
router.post("/agent/ai/switch", async (req: Request, res: Response) => {
    const { provider } = req.body as { provider?: "openai" | "gemini" };

    if (!provider) {
        return res.status(400).json({ error: "Missing provider field" });
    }

    try {
        aiProvider.setProvider(provider);
        res.json({
            success: true,
            currentProvider: provider,
            status: aiProvider.getStatus()
        });
    } catch (error) {
        res.status(400).json({
            error: error instanceof Error ? error.message : "Failed to switch provider"
        });
    }
});

// ── GET /agent/decisions ──────────────────────────────────────────────
router.get("/agent/decisions", (req: Request, res: Response) => {
    const limit = Math.min(Number(req.query.limit ?? 50), 200);
    const offset = Number(req.query.offset ?? 0);
    res.json({ decisions: getDecisions(limit, offset), stats: getStats() });
});

// ── POST /webhook/delivery ────────────────────────────────────────────
router.post("/webhook/delivery", async (req: Request, res: Response) => {
    return enqueueEvent(req, req.app.locals.queue, "delivery", res);
});

// ── POST /webhook/milestone ───────────────────────────────────────────
router.post("/webhook/milestone", async (req: Request, res: Response) => {
    return enqueueEvent(req, req.app.locals.queue, "milestone", res);
});

// ── POST /oracle/input  (manual override) ─────────────────────────────
router.post("/oracle/input", async (req: Request, res: Response) => {
    return enqueueEvent(req, req.app.locals.queue, "oracle", res);
});

// ── GET /demo/setup ───────────────────────────────────────────────────
router.get("/demo/setup", async (req: Request, res: Response) => {
    const address = await agentWallet.getAddress();
    res.json({
        message: "AgentPay demo — copy these curl commands",
        step1_delivery: {
            curl: `curl -X POST http://localhost:3001/webhook/delivery -H 'Content-Type: application/json' -d '${JSON.stringify({
                deliveryId: `del-${Date.now()}`,
                escrowId: "escrow-demo-001",
                amount: "50.00",
                recipient: address,
                status: "completed",
                metadata: { courier: "FastShip Co.", route: "NYC→LA", proof: "https://proof.example.com/001" },
            })}'`,
        },
        step2_milestone: {
            curl: `curl -X POST http://localhost:3001/webhook/milestone -H 'Content-Type: application/json' -d '${JSON.stringify({
                deliveryId: `ms-${Date.now()}`,
                escrowId: "escrow-milestone-001",
                amount: "0",
                recipient: address,
                status: "milestone_reached",
            })}'`,
        },
        step3_decisions: "curl http://localhost:3001/agent/decisions",
    });
});

// Helper function to enqueue events
async function enqueueEvent(req: express.Request, queue: Queue, eventType: string, res: express.Response) {
    try {
        const event = req.body as DeliveryEvent;
        const fraudScore = await hashEvent(event);

        await queue.add(eventType, event, {
            attempts: 3,
            backoff: { type: 'exponential', delay: 2000 },
            removeOnComplete: 100,
            removeOnFail: 50,
        });

        res.json({
            queued: true,
            eventId: `${eventType}-${Date.now()}`,
            fraudScore
        });
    } catch (error) {
        res.status(400).json({
            error: error instanceof Error ? error.message : "Invalid JSON"
        });
    }
}

export default router;
